language: java

after_success:
  - mvn clean cobertura:cobertura coveralls:report



deploy:
  provider: heroku
  api_key:
    secure: 3fd51bf7-738c-41ec-b371-c989a2cb49e6
  app: api-test-lucas
  on:
    repo: LucasN7Alves/01-calculadora-noturno
